// No-op stub the aha* Electron APIs the donor (plain "Trae") Electron dropped
// but the TRAE SOLO payload still imports.
//
// Background: the macOS DMG payload does `import { ahaAccessibility, ahaCustomException,
// ... } from "electron"`. ByteDance's patched Electron exports these, but the plain
// "Trae" 1.107.1 Linux donor we use as the runtime source removed/renamed exactly
// ahaAccessibility + ahaCustomException (observability/accessibility hooks; the
// payload already guards `if (!k3) return warn('unavailable')`). ESM named imports
// are resolved at link time and cannot be added to the `electron` built-in from JS,
// so we (a) create a node_modules shim that exports no-op objects for the missing
// names and (b) rewrite the payload's affected `import { ... } from "electron"` to
// source those names from the shim. Any real co-imported symbols (app, ahaNet,
// ahaDeviceService, ...) stay on "electron" so the forked runtime still backs them.
//
// Idempotent. Override the stub list with TRAE_AHA_STUBS=name1,name2.
"use strict";
const fs = require("node:fs");
const path = require("node:path");

const APP_ROOT = process.argv[2];
const SHIM_NAME = "__aha-electron-shim";
const MISSING = (process.env.TRAE_AHA_STUBS || "ahaAccessibility,ahaCustomException")
  .split(",").map(s => s.trim()).filter(Boolean);
if (!APP_ROOT) { console.error("usage: patch_aha_shim.js <app_root>"); process.exit(2); }

// --- 1. create the shim package under node_modules (resolvable as a bare import) ---
const shimDir = path.join(APP_ROOT, "node_modules", SHIM_NAME);
fs.mkdirSync(shimDir, { recursive: true });
fs.writeFileSync(path.join(shimDir, "package.json"),
  JSON.stringify({ name: SHIM_NAME, version: "1.0.0", type: "module", main: "index.js" }, null, 2));
// A Proxy that turns ANY property into a no-op function returning undefined. This
// absorbs every method call site (setAutoDetectEnabled / setThrottle / report / ...)
// without throwing, which is what the payload's own `if (!k3)` guards expect.
const indexJs =
  "// Auto-generated by trae-solo (patch_aha_shim.js). No-op stubs for aha* APIs\n" +
  "// the donor Electron dropped. Real aha* (ahaNet/ahaDeviceService/...) stay on 'electron'.\n" +
  "const __noop = new Proxy({}, { get: () => () => undefined });\n" +
  MISSING.map(n => `export const ${n} = __noop;`).join("\n") + "\n";
fs.writeFileSync(path.join(shimDir, "index.js"), indexJs);

// --- 2. rewrite import statements that reference a missing aha* symbol ---
// Matches `import { specifiers } from "electron"` (single or double quotes, any ws).
// Splits specifiers: real ones stay on "electron"; missing ones come from the shim.
const OUT = path.join(APP_ROOT, "out");
if (!fs.existsSync(OUT)) { console.error("[aha-shim] no out/ dir at " + OUT); process.exit(0); }

const re = /import\s*\{([^}]*)\}\s*from\s*(["'])electron\2/g;
let filesTouched = 0, stmtsRewritten = 0;

function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.isFile() && p.endsWith(".js")) transform(p);
  }
}
function transform(file) {
  const src = fs.readFileSync(file, "utf8");
  let changed = false;
  const out = src.replace(re, (m, spec, q) => {
    const parts = spec.split(",").map(s => s.trim()).filter(Boolean);
    const real = [], miss = [];
    for (const p of parts) {
      const name = p.split(/\s+as\s+/)[0].trim();
      (MISSING.includes(name) ? miss : real).push(p);
    }
    if (!miss.length) return m;                 // statement unaffected
    changed = true; stmtsRewritten++;
    let s = "";
    if (real.length) s += `import{${real.join(",")}}from${q}electron${q};`;
    s += `import{${miss.join(",")}}from${q}${SHIM_NAME}${q}`;
    return s;
  });
  if (changed) { fs.writeFileSync(file, out); filesTouched++; }
}

walk(OUT);
console.error(`[aha-shim] stubbed {${MISSING.join(", ")}} -> node_modules/${SHIM_NAME}; ` +
              `files=${filesTouched} statements=${stmtsRewritten}`);
